function [fitresult, gof] = createFit_nscf(alpha, nscf)
%CREATEFIT(ALPHA,NSCF)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : alpha
%      Y Output: nscf
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Mar-2020 18:56:52


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( alpha, nscf );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% % Plot fit with data.
% figure(1);
% h = plot( fitresult, xData, yData );
% % Label axes
% grid on
% hold on


